version: "3.8"
services:
  dev-postgres: # Container Name
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trivial-todo-db
    restart: always
    networks:
      - lesson
networks:
  lesson: